// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Phpipam
{
    [PhpipamResourceType("phpipam:index/address:Address")]
    public partial class Address : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the IP address in the PHPIPAM database.
        /// </summary>
        [Output("addressId")]
        public Output<int> AddressId { get; private set; } = null!;

        /// <summary>
        /// A key/value map of custom fields for this address.
        /// 
        /// ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
        /// all fields set to optional when using this plugin. For more info see
        /// [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
        /// ensure that your fields also do not have default values, or ensure the default
        /// is set in your TF configuration. Diff loops may happen otherwise!
        /// Custom fileds must contain mandatory prefix `custom_`.
        /// </summary>
        [Output("customFields")]
        public Output<ImmutableDictionary<string, object>?> CustomFields { get; private set; } = null!;

        /// <summary>
        /// The description provided to this IP address.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The ID of the associated device in the PHPIPAM
        /// database.
        /// </summary>
        [Output("deviceId")]
        public Output<int> DeviceId { get; private set; } = null!;

        /// <summary>
        /// The last time this resource was modified.
        /// </summary>
        [Output("editDate")]
        public Output<string> EditDate { get; private set; } = null!;

        /// <summary>
        /// `true` if this address is excluded from ping
        /// probes.
        /// </summary>
        [Output("excludePing")]
        public Output<bool> ExcludePing { get; private set; } = null!;

        /// <summary>
        /// The hostname supplied to this IP address.
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// The IP address to reserve.
        /// </summary>
        [Output("ipAddress")]
        public Output<string> IpAddress { get; private set; } = null!;

        /// <summary>
        /// `true` if this IP address has been designated as a
        /// gateway.
        /// </summary>
        [Output("isGateway")]
        public Output<bool> IsGateway { get; private set; } = null!;

        /// <summary>
        /// The last time this IP address answered ping probes.
        /// </summary>
        [Output("lastSeen")]
        public Output<string> LastSeen { get; private set; } = null!;

        /// <summary>
        /// The MAC address provided to this IP address.
        /// </summary>
        [Output("macAddress")]
        public Output<string> MacAddress { get; private set; } = null!;

        /// <summary>
        /// The note supplied to this IP address.
        /// </summary>
        [Output("note")]
        public Output<string> Note { get; private set; } = null!;

        /// <summary>
        /// The owner name provided to this IP address.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        /// <summary>
        /// The ID of the associated PTR record in the
        /// PHPIPAM database.
        /// </summary>
        [Output("ptrRecordId")]
        public Output<int> PtrRecordId { get; private set; } = null!;

        [Output("removeDnsOnDelete")]
        public Output<bool?> RemoveDnsOnDelete { get; private set; } = null!;

        /// <summary>
        /// `true` if PTR records are not being created
        /// for this IP address.
        /// </summary>
        [Output("skipPtrRecord")]
        public Output<bool> SkipPtrRecord { get; private set; } = null!;

        /// <summary>
        /// The tag ID in the database for the IP address'
        /// specific state. **NOTE:** This is currently represented as an integer but may
        /// change to the specific string representation at a later time.
        /// </summary>
        [Output("stateTagId")]
        public Output<int> StateTagId { get; private set; } = null!;

        /// <summary>
        /// The database ID of the subnet this IP address
        /// belongs to.
        /// </summary>
        [Output("subnetId")]
        public Output<int> SubnetId { get; private set; } = null!;

        /// <summary>
        /// A string port label that is associated with
        /// this address.
        /// </summary>
        [Output("switchPortLabel")]
        public Output<string> SwitchPortLabel { get; private set; } = null!;


        /// <summary>
        /// Create a Address resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Address(string name, AddressArgs args, CustomResourceOptions? options = null)
            : base("phpipam:index/address:Address", name, args ?? new AddressArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Address(string name, Input<string> id, AddressState? state = null, CustomResourceOptions? options = null)
            : base("phpipam:index/address:Address", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Address resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Address Get(string name, Input<string> id, AddressState? state = null, CustomResourceOptions? options = null)
        {
            return new Address(name, id, state, options);
        }
    }

    public sealed class AddressArgs : global::Pulumi.ResourceArgs
    {
        [Input("customFields")]
        private InputMap<object>? _customFields;

        /// <summary>
        /// A key/value map of custom fields for this address.
        /// 
        /// ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
        /// all fields set to optional when using this plugin. For more info see
        /// [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
        /// ensure that your fields also do not have default values, or ensure the default
        /// is set in your TF configuration. Diff loops may happen otherwise!
        /// Custom fileds must contain mandatory prefix `custom_`.
        /// </summary>
        public InputMap<object> CustomFields
        {
            get => _customFields ?? (_customFields = new InputMap<object>());
            set => _customFields = value;
        }

        /// <summary>
        /// The description provided to this IP address.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the associated device in the PHPIPAM
        /// database.
        /// </summary>
        [Input("deviceId")]
        public Input<int>? DeviceId { get; set; }

        /// <summary>
        /// `true` if this address is excluded from ping
        /// probes.
        /// </summary>
        [Input("excludePing")]
        public Input<bool>? ExcludePing { get; set; }

        /// <summary>
        /// The hostname supplied to this IP address.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The IP address to reserve.
        /// </summary>
        [Input("ipAddress")]
        public Input<string>? IpAddress { get; set; }

        /// <summary>
        /// `true` if this IP address has been designated as a
        /// gateway.
        /// </summary>
        [Input("isGateway")]
        public Input<bool>? IsGateway { get; set; }

        /// <summary>
        /// The MAC address provided to this IP address.
        /// </summary>
        [Input("macAddress")]
        public Input<string>? MacAddress { get; set; }

        /// <summary>
        /// The note supplied to this IP address.
        /// </summary>
        [Input("note")]
        public Input<string>? Note { get; set; }

        /// <summary>
        /// The owner name provided to this IP address.
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// The ID of the associated PTR record in the
        /// PHPIPAM database.
        /// </summary>
        [Input("ptrRecordId")]
        public Input<int>? PtrRecordId { get; set; }

        [Input("removeDnsOnDelete")]
        public Input<bool>? RemoveDnsOnDelete { get; set; }

        /// <summary>
        /// `true` if PTR records are not being created
        /// for this IP address.
        /// </summary>
        [Input("skipPtrRecord")]
        public Input<bool>? SkipPtrRecord { get; set; }

        /// <summary>
        /// The tag ID in the database for the IP address'
        /// specific state. **NOTE:** This is currently represented as an integer but may
        /// change to the specific string representation at a later time.
        /// </summary>
        [Input("stateTagId")]
        public Input<int>? StateTagId { get; set; }

        /// <summary>
        /// The database ID of the subnet this IP address
        /// belongs to.
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<int> SubnetId { get; set; } = null!;

        /// <summary>
        /// A string port label that is associated with
        /// this address.
        /// </summary>
        [Input("switchPortLabel")]
        public Input<string>? SwitchPortLabel { get; set; }

        public AddressArgs()
        {
        }
        public static new AddressArgs Empty => new AddressArgs();
    }

    public sealed class AddressState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the IP address in the PHPIPAM database.
        /// </summary>
        [Input("addressId")]
        public Input<int>? AddressId { get; set; }

        [Input("customFields")]
        private InputMap<object>? _customFields;

        /// <summary>
        /// A key/value map of custom fields for this address.
        /// 
        /// ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
        /// all fields set to optional when using this plugin. For more info see
        /// [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
        /// ensure that your fields also do not have default values, or ensure the default
        /// is set in your TF configuration. Diff loops may happen otherwise!
        /// Custom fileds must contain mandatory prefix `custom_`.
        /// </summary>
        public InputMap<object> CustomFields
        {
            get => _customFields ?? (_customFields = new InputMap<object>());
            set => _customFields = value;
        }

        /// <summary>
        /// The description provided to this IP address.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The ID of the associated device in the PHPIPAM
        /// database.
        /// </summary>
        [Input("deviceId")]
        public Input<int>? DeviceId { get; set; }

        /// <summary>
        /// The last time this resource was modified.
        /// </summary>
        [Input("editDate")]
        public Input<string>? EditDate { get; set; }

        /// <summary>
        /// `true` if this address is excluded from ping
        /// probes.
        /// </summary>
        [Input("excludePing")]
        public Input<bool>? ExcludePing { get; set; }

        /// <summary>
        /// The hostname supplied to this IP address.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The IP address to reserve.
        /// </summary>
        [Input("ipAddress")]
        public Input<string>? IpAddress { get; set; }

        /// <summary>
        /// `true` if this IP address has been designated as a
        /// gateway.
        /// </summary>
        [Input("isGateway")]
        public Input<bool>? IsGateway { get; set; }

        /// <summary>
        /// The last time this IP address answered ping probes.
        /// </summary>
        [Input("lastSeen")]
        public Input<string>? LastSeen { get; set; }

        /// <summary>
        /// The MAC address provided to this IP address.
        /// </summary>
        [Input("macAddress")]
        public Input<string>? MacAddress { get; set; }

        /// <summary>
        /// The note supplied to this IP address.
        /// </summary>
        [Input("note")]
        public Input<string>? Note { get; set; }

        /// <summary>
        /// The owner name provided to this IP address.
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// The ID of the associated PTR record in the
        /// PHPIPAM database.
        /// </summary>
        [Input("ptrRecordId")]
        public Input<int>? PtrRecordId { get; set; }

        [Input("removeDnsOnDelete")]
        public Input<bool>? RemoveDnsOnDelete { get; set; }

        /// <summary>
        /// `true` if PTR records are not being created
        /// for this IP address.
        /// </summary>
        [Input("skipPtrRecord")]
        public Input<bool>? SkipPtrRecord { get; set; }

        /// <summary>
        /// The tag ID in the database for the IP address'
        /// specific state. **NOTE:** This is currently represented as an integer but may
        /// change to the specific string representation at a later time.
        /// </summary>
        [Input("stateTagId")]
        public Input<int>? StateTagId { get; set; }

        /// <summary>
        /// The database ID of the subnet this IP address
        /// belongs to.
        /// </summary>
        [Input("subnetId")]
        public Input<int>? SubnetId { get; set; }

        /// <summary>
        /// A string port label that is associated with
        /// this address.
        /// </summary>
        [Input("switchPortLabel")]
        public Input<string>? SwitchPortLabel { get; set; }

        public AddressState()
        {
        }
        public static new AddressState Empty => new AddressState();
    }
}
