// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Phpipam
{
    [PhpipamResourceType("phpipam:index/l2domain:L2domain")]
    public partial class L2domain : global::Pulumi.CustomResource
    {
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("domainId")]
        public Output<int> DomainId { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("sections")]
        public Output<string> Sections { get; private set; } = null!;


        /// <summary>
        /// Create a L2domain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public L2domain(string name, L2domainArgs? args = null, CustomResourceOptions? options = null)
            : base("phpipam:index/l2domain:L2domain", name, args ?? new L2domainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private L2domain(string name, Input<string> id, L2domainState? state = null, CustomResourceOptions? options = null)
            : base("phpipam:index/l2domain:L2domain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing L2domain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static L2domain Get(string name, Input<string> id, L2domainState? state = null, CustomResourceOptions? options = null)
        {
            return new L2domain(name, id, state, options);
        }
    }

    public sealed class L2domainArgs : global::Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("sections")]
        public Input<string>? Sections { get; set; }

        public L2domainArgs()
        {
        }
        public static new L2domainArgs Empty => new L2domainArgs();
    }

    public sealed class L2domainState : global::Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domainId")]
        public Input<int>? DomainId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("sections")]
        public Input<string>? Sections { get; set; }

        public L2domainState()
        {
        }
        public static new L2domainState Empty => new L2domainState();
    }
}
