# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetVlanResult',
    'AwaitableGetVlanResult',
    'get_vlan',
    'get_vlan_output',
]

@pulumi.output_type
class GetVlanResult:
    """
    A collection of values returned by getVlan.
    """
    def __init__(__self__, custom_fields=None, description=None, edit_date=None, id=None, l2_domain_id=None, name=None, number=None, vlan_id=None):
        if custom_fields and not isinstance(custom_fields, dict):
            raise TypeError("Expected argument 'custom_fields' to be a dict")
        pulumi.set(__self__, "custom_fields", custom_fields)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if edit_date and not isinstance(edit_date, str):
            raise TypeError("Expected argument 'edit_date' to be a str")
        pulumi.set(__self__, "edit_date", edit_date)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if l2_domain_id and not isinstance(l2_domain_id, int):
            raise TypeError("Expected argument 'l2_domain_id' to be a int")
        pulumi.set(__self__, "l2_domain_id", l2_domain_id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if number and not isinstance(number, int):
            raise TypeError("Expected argument 'number' to be a int")
        pulumi.set(__self__, "number", number)
        if vlan_id and not isinstance(vlan_id, int):
            raise TypeError("Expected argument 'vlan_id' to be a int")
        pulumi.set(__self__, "vlan_id", vlan_id)

    @property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Mapping[str, Any]:
        """
        A key/value map of custom fields for this VLAN.
        """
        return pulumi.get(self, "custom_fields")

    @property
    @pulumi.getter
    def description(self) -> str:
        """
        The description supplied to the VLAN.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="editDate")
    def edit_date(self) -> str:
        """
        The date this resource was last updated.
        """
        return pulumi.get(self, "edit_date")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="l2DomainId")
    def l2_domain_id(self) -> int:
        """
        The layer 2 domain ID in the PHPIPAM database.
        """
        return pulumi.get(self, "l2_domain_id")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        The name/label of the VLAN.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def number(self) -> int:
        """
        The number of the VLAN (the actual VLAN ID on your switch).
        """
        return pulumi.get(self, "number")

    @property
    @pulumi.getter(name="vlanId")
    def vlan_id(self) -> int:
        """
        The ID of the VLAN to look up. **NOTE:** this is the database ID,
        not the VLAN number - if you need this, use the `number` parameter.
        """
        return pulumi.get(self, "vlan_id")


class AwaitableGetVlanResult(GetVlanResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVlanResult(
            custom_fields=self.custom_fields,
            description=self.description,
            edit_date=self.edit_date,
            id=self.id,
            l2_domain_id=self.l2_domain_id,
            name=self.name,
            number=self.number,
            vlan_id=self.vlan_id)


def get_vlan(l2_domain_id: Optional[int] = None,
             number: Optional[int] = None,
             vlan_id: Optional[int] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVlanResult:
    """
    ## # Vlan

    The `Vlan` data source allows one to look up a VLAN in the PHPIPAM
    database. This can then be used to assign a VLAN to a subnet in the
    `Subnet` resource. It can also be used
    to gather other information on the VLAN.

    **Example:**

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_phpipam as phpipam

    section = phpipam.get_section(name="Customers")
    vlan = phpipam.get_vlan(number=1000)
    subnet = phpipam.Subnet("subnet",
        section_id=section.section_id,
        subnet_address="10.10.3.0",
        subnet_mask=24,
        vlan_id=vlan.vlan_id)
    ```
    <!--End PulumiCodeChooser -->


    :param int l2_domain_id: The layer 2 domain ID in the PHPIPAM database.
    :param int number: The number of the VLAN to look up.
           
           One of `vlan_id` or `number` must be supplied. If both are supplied,
           `vlan_id` is used.
    :param int vlan_id: The ID of the VLAN to look up. **NOTE:** this is the database ID,
           not the VLAN number - if you need this, use the `number` parameter.
    """
    __args__ = dict()
    __args__['l2DomainId'] = l2_domain_id
    __args__['number'] = number
    __args__['vlanId'] = vlan_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('phpipam:index/getVlan:getVlan', __args__, opts=opts, typ=GetVlanResult).value

    return AwaitableGetVlanResult(
        custom_fields=pulumi.get(__ret__, 'custom_fields'),
        description=pulumi.get(__ret__, 'description'),
        edit_date=pulumi.get(__ret__, 'edit_date'),
        id=pulumi.get(__ret__, 'id'),
        l2_domain_id=pulumi.get(__ret__, 'l2_domain_id'),
        name=pulumi.get(__ret__, 'name'),
        number=pulumi.get(__ret__, 'number'),
        vlan_id=pulumi.get(__ret__, 'vlan_id'))


@_utilities.lift_output_func(get_vlan)
def get_vlan_output(l2_domain_id: Optional[pulumi.Input[Optional[int]]] = None,
                    number: Optional[pulumi.Input[Optional[int]]] = None,
                    vlan_id: Optional[pulumi.Input[Optional[int]]] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetVlanResult]:
    """
    ## # Vlan

    The `Vlan` data source allows one to look up a VLAN in the PHPIPAM
    database. This can then be used to assign a VLAN to a subnet in the
    `Subnet` resource. It can also be used
    to gather other information on the VLAN.

    **Example:**

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_phpipam as phpipam

    section = phpipam.get_section(name="Customers")
    vlan = phpipam.get_vlan(number=1000)
    subnet = phpipam.Subnet("subnet",
        section_id=section.section_id,
        subnet_address="10.10.3.0",
        subnet_mask=24,
        vlan_id=vlan.vlan_id)
    ```
    <!--End PulumiCodeChooser -->


    :param int l2_domain_id: The layer 2 domain ID in the PHPIPAM database.
    :param int number: The number of the VLAN to look up.
           
           One of `vlan_id` or `number` must be supplied. If both are supplied,
           `vlan_id` is used.
    :param int vlan_id: The ID of the VLAN to look up. **NOTE:** this is the database ID,
           not the VLAN number - if you need this, use the `number` parameter.
    """
    ...
