// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("phpipam");

/**
 * The application ID required for API requests
 */
export declare const appId: string | undefined;
Object.defineProperty(exports, "appId", {
    get() {
        return __config.get("appId");
    },
    enumerable: true,
});

/**
 * The full URL (plus path) to the API endpoint
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * Whether server should be accessed without verifying the TLS certificate.
 */
export declare const insecure: boolean | undefined;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure");
    },
    enumerable: true,
});

/**
 * Whether the API client is configured to nest custom values.
 */
export declare const nestCustomFields: boolean | undefined;
Object.defineProperty(exports, "nestCustomFields", {
    get() {
        return __config.getObject<boolean>("nestCustomFields");
    },
    enumerable: true,
});

/**
 * The password of the PHPIPAM account
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * The username of the PHPIPAM account
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

