// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package phpipam

import (
	"context"
	"reflect"

	"errors"
	"github.com/DBACHRY13/pulumi-phpipam/sdk/go/phpipam/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FirstFreeAddress struct {
	pulumi.CustomResourceState

	AddressId       pulumi.IntOutput    `pulumi:"addressId"`
	CustomFields    pulumi.MapOutput    `pulumi:"customFields"`
	Description     pulumi.StringOutput `pulumi:"description"`
	DeviceId        pulumi.IntOutput    `pulumi:"deviceId"`
	EditDate        pulumi.StringOutput `pulumi:"editDate"`
	ExcludePing     pulumi.BoolOutput   `pulumi:"excludePing"`
	Hostname        pulumi.StringOutput `pulumi:"hostname"`
	IpAddress       pulumi.StringOutput `pulumi:"ipAddress"`
	IsGateway       pulumi.BoolOutput   `pulumi:"isGateway"`
	LastSeen        pulumi.StringOutput `pulumi:"lastSeen"`
	MacAddress      pulumi.StringOutput `pulumi:"macAddress"`
	Note            pulumi.StringOutput `pulumi:"note"`
	Owner           pulumi.StringOutput `pulumi:"owner"`
	PtrRecordId     pulumi.IntOutput    `pulumi:"ptrRecordId"`
	SkipPtrRecord   pulumi.BoolOutput   `pulumi:"skipPtrRecord"`
	StateTagId      pulumi.IntOutput    `pulumi:"stateTagId"`
	SubnetId        pulumi.IntOutput    `pulumi:"subnetId"`
	SwitchPortLabel pulumi.StringOutput `pulumi:"switchPortLabel"`
}

// NewFirstFreeAddress registers a new resource with the given unique name, arguments, and options.
func NewFirstFreeAddress(ctx *pulumi.Context,
	name string, args *FirstFreeAddressArgs, opts ...pulumi.ResourceOption) (*FirstFreeAddress, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SubnetId == nil {
		return nil, errors.New("invalid value for required argument 'SubnetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FirstFreeAddress
	err := ctx.RegisterResource("phpipam:index/firstFreeAddress:FirstFreeAddress", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFirstFreeAddress gets an existing FirstFreeAddress resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFirstFreeAddress(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FirstFreeAddressState, opts ...pulumi.ResourceOption) (*FirstFreeAddress, error) {
	var resource FirstFreeAddress
	err := ctx.ReadResource("phpipam:index/firstFreeAddress:FirstFreeAddress", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FirstFreeAddress resources.
type firstFreeAddressState struct {
	AddressId       *int                   `pulumi:"addressId"`
	CustomFields    map[string]interface{} `pulumi:"customFields"`
	Description     *string                `pulumi:"description"`
	DeviceId        *int                   `pulumi:"deviceId"`
	EditDate        *string                `pulumi:"editDate"`
	ExcludePing     *bool                  `pulumi:"excludePing"`
	Hostname        *string                `pulumi:"hostname"`
	IpAddress       *string                `pulumi:"ipAddress"`
	IsGateway       *bool                  `pulumi:"isGateway"`
	LastSeen        *string                `pulumi:"lastSeen"`
	MacAddress      *string                `pulumi:"macAddress"`
	Note            *string                `pulumi:"note"`
	Owner           *string                `pulumi:"owner"`
	PtrRecordId     *int                   `pulumi:"ptrRecordId"`
	SkipPtrRecord   *bool                  `pulumi:"skipPtrRecord"`
	StateTagId      *int                   `pulumi:"stateTagId"`
	SubnetId        *int                   `pulumi:"subnetId"`
	SwitchPortLabel *string                `pulumi:"switchPortLabel"`
}

type FirstFreeAddressState struct {
	AddressId       pulumi.IntPtrInput
	CustomFields    pulumi.MapInput
	Description     pulumi.StringPtrInput
	DeviceId        pulumi.IntPtrInput
	EditDate        pulumi.StringPtrInput
	ExcludePing     pulumi.BoolPtrInput
	Hostname        pulumi.StringPtrInput
	IpAddress       pulumi.StringPtrInput
	IsGateway       pulumi.BoolPtrInput
	LastSeen        pulumi.StringPtrInput
	MacAddress      pulumi.StringPtrInput
	Note            pulumi.StringPtrInput
	Owner           pulumi.StringPtrInput
	PtrRecordId     pulumi.IntPtrInput
	SkipPtrRecord   pulumi.BoolPtrInput
	StateTagId      pulumi.IntPtrInput
	SubnetId        pulumi.IntPtrInput
	SwitchPortLabel pulumi.StringPtrInput
}

func (FirstFreeAddressState) ElementType() reflect.Type {
	return reflect.TypeOf((*firstFreeAddressState)(nil)).Elem()
}

type firstFreeAddressArgs struct {
	CustomFields    map[string]interface{} `pulumi:"customFields"`
	Description     *string                `pulumi:"description"`
	DeviceId        *int                   `pulumi:"deviceId"`
	ExcludePing     *bool                  `pulumi:"excludePing"`
	Hostname        *string                `pulumi:"hostname"`
	IsGateway       *bool                  `pulumi:"isGateway"`
	MacAddress      *string                `pulumi:"macAddress"`
	Note            *string                `pulumi:"note"`
	Owner           *string                `pulumi:"owner"`
	PtrRecordId     *int                   `pulumi:"ptrRecordId"`
	SkipPtrRecord   *bool                  `pulumi:"skipPtrRecord"`
	StateTagId      *int                   `pulumi:"stateTagId"`
	SubnetId        int                    `pulumi:"subnetId"`
	SwitchPortLabel *string                `pulumi:"switchPortLabel"`
}

// The set of arguments for constructing a FirstFreeAddress resource.
type FirstFreeAddressArgs struct {
	CustomFields    pulumi.MapInput
	Description     pulumi.StringPtrInput
	DeviceId        pulumi.IntPtrInput
	ExcludePing     pulumi.BoolPtrInput
	Hostname        pulumi.StringPtrInput
	IsGateway       pulumi.BoolPtrInput
	MacAddress      pulumi.StringPtrInput
	Note            pulumi.StringPtrInput
	Owner           pulumi.StringPtrInput
	PtrRecordId     pulumi.IntPtrInput
	SkipPtrRecord   pulumi.BoolPtrInput
	StateTagId      pulumi.IntPtrInput
	SubnetId        pulumi.IntInput
	SwitchPortLabel pulumi.StringPtrInput
}

func (FirstFreeAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*firstFreeAddressArgs)(nil)).Elem()
}

type FirstFreeAddressInput interface {
	pulumi.Input

	ToFirstFreeAddressOutput() FirstFreeAddressOutput
	ToFirstFreeAddressOutputWithContext(ctx context.Context) FirstFreeAddressOutput
}

func (*FirstFreeAddress) ElementType() reflect.Type {
	return reflect.TypeOf((**FirstFreeAddress)(nil)).Elem()
}

func (i *FirstFreeAddress) ToFirstFreeAddressOutput() FirstFreeAddressOutput {
	return i.ToFirstFreeAddressOutputWithContext(context.Background())
}

func (i *FirstFreeAddress) ToFirstFreeAddressOutputWithContext(ctx context.Context) FirstFreeAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirstFreeAddressOutput)
}

// FirstFreeAddressArrayInput is an input type that accepts FirstFreeAddressArray and FirstFreeAddressArrayOutput values.
// You can construct a concrete instance of `FirstFreeAddressArrayInput` via:
//
//	FirstFreeAddressArray{ FirstFreeAddressArgs{...} }
type FirstFreeAddressArrayInput interface {
	pulumi.Input

	ToFirstFreeAddressArrayOutput() FirstFreeAddressArrayOutput
	ToFirstFreeAddressArrayOutputWithContext(context.Context) FirstFreeAddressArrayOutput
}

type FirstFreeAddressArray []FirstFreeAddressInput

func (FirstFreeAddressArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirstFreeAddress)(nil)).Elem()
}

func (i FirstFreeAddressArray) ToFirstFreeAddressArrayOutput() FirstFreeAddressArrayOutput {
	return i.ToFirstFreeAddressArrayOutputWithContext(context.Background())
}

func (i FirstFreeAddressArray) ToFirstFreeAddressArrayOutputWithContext(ctx context.Context) FirstFreeAddressArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirstFreeAddressArrayOutput)
}

// FirstFreeAddressMapInput is an input type that accepts FirstFreeAddressMap and FirstFreeAddressMapOutput values.
// You can construct a concrete instance of `FirstFreeAddressMapInput` via:
//
//	FirstFreeAddressMap{ "key": FirstFreeAddressArgs{...} }
type FirstFreeAddressMapInput interface {
	pulumi.Input

	ToFirstFreeAddressMapOutput() FirstFreeAddressMapOutput
	ToFirstFreeAddressMapOutputWithContext(context.Context) FirstFreeAddressMapOutput
}

type FirstFreeAddressMap map[string]FirstFreeAddressInput

func (FirstFreeAddressMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirstFreeAddress)(nil)).Elem()
}

func (i FirstFreeAddressMap) ToFirstFreeAddressMapOutput() FirstFreeAddressMapOutput {
	return i.ToFirstFreeAddressMapOutputWithContext(context.Background())
}

func (i FirstFreeAddressMap) ToFirstFreeAddressMapOutputWithContext(ctx context.Context) FirstFreeAddressMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirstFreeAddressMapOutput)
}

type FirstFreeAddressOutput struct{ *pulumi.OutputState }

func (FirstFreeAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FirstFreeAddress)(nil)).Elem()
}

func (o FirstFreeAddressOutput) ToFirstFreeAddressOutput() FirstFreeAddressOutput {
	return o
}

func (o FirstFreeAddressOutput) ToFirstFreeAddressOutputWithContext(ctx context.Context) FirstFreeAddressOutput {
	return o
}

func (o FirstFreeAddressOutput) AddressId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.IntOutput { return v.AddressId }).(pulumi.IntOutput)
}

func (o FirstFreeAddressOutput) CustomFields() pulumi.MapOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.MapOutput { return v.CustomFields }).(pulumi.MapOutput)
}

func (o FirstFreeAddressOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) DeviceId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.IntOutput { return v.DeviceId }).(pulumi.IntOutput)
}

func (o FirstFreeAddressOutput) EditDate() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.EditDate }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) ExcludePing() pulumi.BoolOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.BoolOutput { return v.ExcludePing }).(pulumi.BoolOutput)
}

func (o FirstFreeAddressOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.IpAddress }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) IsGateway() pulumi.BoolOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.BoolOutput { return v.IsGateway }).(pulumi.BoolOutput)
}

func (o FirstFreeAddressOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.LastSeen }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) Note() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.Note }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

func (o FirstFreeAddressOutput) PtrRecordId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.IntOutput { return v.PtrRecordId }).(pulumi.IntOutput)
}

func (o FirstFreeAddressOutput) SkipPtrRecord() pulumi.BoolOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.BoolOutput { return v.SkipPtrRecord }).(pulumi.BoolOutput)
}

func (o FirstFreeAddressOutput) StateTagId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.IntOutput { return v.StateTagId }).(pulumi.IntOutput)
}

func (o FirstFreeAddressOutput) SubnetId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.IntOutput { return v.SubnetId }).(pulumi.IntOutput)
}

func (o FirstFreeAddressOutput) SwitchPortLabel() pulumi.StringOutput {
	return o.ApplyT(func(v *FirstFreeAddress) pulumi.StringOutput { return v.SwitchPortLabel }).(pulumi.StringOutput)
}

type FirstFreeAddressArrayOutput struct{ *pulumi.OutputState }

func (FirstFreeAddressArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirstFreeAddress)(nil)).Elem()
}

func (o FirstFreeAddressArrayOutput) ToFirstFreeAddressArrayOutput() FirstFreeAddressArrayOutput {
	return o
}

func (o FirstFreeAddressArrayOutput) ToFirstFreeAddressArrayOutputWithContext(ctx context.Context) FirstFreeAddressArrayOutput {
	return o
}

func (o FirstFreeAddressArrayOutput) Index(i pulumi.IntInput) FirstFreeAddressOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FirstFreeAddress {
		return vs[0].([]*FirstFreeAddress)[vs[1].(int)]
	}).(FirstFreeAddressOutput)
}

type FirstFreeAddressMapOutput struct{ *pulumi.OutputState }

func (FirstFreeAddressMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirstFreeAddress)(nil)).Elem()
}

func (o FirstFreeAddressMapOutput) ToFirstFreeAddressMapOutput() FirstFreeAddressMapOutput {
	return o
}

func (o FirstFreeAddressMapOutput) ToFirstFreeAddressMapOutputWithContext(ctx context.Context) FirstFreeAddressMapOutput {
	return o
}

func (o FirstFreeAddressMapOutput) MapIndex(k pulumi.StringInput) FirstFreeAddressOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FirstFreeAddress {
		return vs[0].(map[string]*FirstFreeAddress)[vs[1].(string)]
	}).(FirstFreeAddressOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirstFreeAddressInput)(nil)).Elem(), &FirstFreeAddress{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirstFreeAddressArrayInput)(nil)).Elem(), FirstFreeAddressArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirstFreeAddressMapInput)(nil)).Elem(), FirstFreeAddressMap{})
	pulumi.RegisterOutputType(FirstFreeAddressOutput{})
	pulumi.RegisterOutputType(FirstFreeAddressArrayOutput{})
	pulumi.RegisterOutputType(FirstFreeAddressMapOutput{})
}
