// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package phpipam

import (
	"context"
	"reflect"

	"github.com/DBACHRY13/pulumi-phpipam/sdk/go/phpipam/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAddresses(ctx *pulumi.Context, args *GetAddressesArgs, opts ...pulumi.InvokeOption) (*GetAddressesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAddressesResult
	err := ctx.Invoke("phpipam:index/getAddresses:getAddresses", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAddresses.
type GetAddressesArgs struct {
	// A map of custom fields to search for. The filter
	// values are regular expressions that follow the RE2 syntax for which you can
	// find documentation [here](https://github.com/google/re2/wiki/Syntax). All
	// fields need to match for the match to succeed.
	//
	// ⚠️  **NOTE:** An empty or unspecified `customFieldFilter` value is the
	// equivalent to a regular expression that matches everything, and hence will
	// return **all** addresses that contain the referenced custom field key!
	// Custom fileds must contain mandatory prefix `custom_`.
	CustomFieldFilter map[string]interface{} `pulumi:"customFieldFilter"`
	// The description of the IP address. `subnetId` is required
	// when using this field.
	Description *string `pulumi:"description"`
	// The host name of the IP address. `subnetId` is required when
	// using this field.
	Hostname *string `pulumi:"hostname"`
	// The ID of the subnet that the address resides in. This is
	// required to search on the `description` or `hostname` fields.
	//
	// One of the following fields is required alongside `subnetId`:
	SubnetId int `pulumi:"subnetId"`
}

// A collection of values returned by getAddresses.
type GetAddressesResult struct {
	// A list of discovered IP address IDs.
	AddressIds        []int                  `pulumi:"addressIds"`
	CustomFieldFilter map[string]interface{} `pulumi:"customFieldFilter"`
	Description       *string                `pulumi:"description"`
	Hostname          *string                `pulumi:"hostname"`
	// The provider-assigned unique ID for this managed resource.
	Id       string `pulumi:"id"`
	SubnetId int    `pulumi:"subnetId"`
}

func GetAddressesOutput(ctx *pulumi.Context, args GetAddressesOutputArgs, opts ...pulumi.InvokeOption) GetAddressesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAddressesResult, error) {
			args := v.(GetAddressesArgs)
			r, err := GetAddresses(ctx, &args, opts...)
			var s GetAddressesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAddressesResultOutput)
}

// A collection of arguments for invoking getAddresses.
type GetAddressesOutputArgs struct {
	// A map of custom fields to search for. The filter
	// values are regular expressions that follow the RE2 syntax for which you can
	// find documentation [here](https://github.com/google/re2/wiki/Syntax). All
	// fields need to match for the match to succeed.
	//
	// ⚠️  **NOTE:** An empty or unspecified `customFieldFilter` value is the
	// equivalent to a regular expression that matches everything, and hence will
	// return **all** addresses that contain the referenced custom field key!
	// Custom fileds must contain mandatory prefix `custom_`.
	CustomFieldFilter pulumi.MapInput `pulumi:"customFieldFilter"`
	// The description of the IP address. `subnetId` is required
	// when using this field.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The host name of the IP address. `subnetId` is required when
	// using this field.
	Hostname pulumi.StringPtrInput `pulumi:"hostname"`
	// The ID of the subnet that the address resides in. This is
	// required to search on the `description` or `hostname` fields.
	//
	// One of the following fields is required alongside `subnetId`:
	SubnetId pulumi.IntInput `pulumi:"subnetId"`
}

func (GetAddressesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAddressesArgs)(nil)).Elem()
}

// A collection of values returned by getAddresses.
type GetAddressesResultOutput struct{ *pulumi.OutputState }

func (GetAddressesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAddressesResult)(nil)).Elem()
}

func (o GetAddressesResultOutput) ToGetAddressesResultOutput() GetAddressesResultOutput {
	return o
}

func (o GetAddressesResultOutput) ToGetAddressesResultOutputWithContext(ctx context.Context) GetAddressesResultOutput {
	return o
}

// A list of discovered IP address IDs.
func (o GetAddressesResultOutput) AddressIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetAddressesResult) []int { return v.AddressIds }).(pulumi.IntArrayOutput)
}

func (o GetAddressesResultOutput) CustomFieldFilter() pulumi.MapOutput {
	return o.ApplyT(func(v GetAddressesResult) map[string]interface{} { return v.CustomFieldFilter }).(pulumi.MapOutput)
}

func (o GetAddressesResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAddressesResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o GetAddressesResultOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAddressesResult) *string { return v.Hostname }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAddressesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAddressesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAddressesResultOutput) SubnetId() pulumi.IntOutput {
	return o.ApplyT(func(v GetAddressesResult) int { return v.SubnetId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAddressesResultOutput{})
}
