# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('phpipam')


class _ExportableConfig(types.ModuleType):
    @property
    def app_id(self) -> Optional[str]:
        """
        The application ID required for API requests
        """
        return __config__.get('appId')

    @property
    def endpoint(self) -> Optional[str]:
        """
        The full URL (plus path) to the API endpoint
        """
        return __config__.get('endpoint')

    @property
    def insecure(self) -> Optional[bool]:
        """
        Whether server should be accessed without verifying the TLS certificate.
        """
        return __config__.get_bool('insecure')

    @property
    def nest_custom_fields(self) -> Optional[bool]:
        """
        Whether the API client is configured to nest custom values.
        """
        return __config__.get_bool('nestCustomFields')

    @property
    def password(self) -> Optional[str]:
        """
        The password of the PHPIPAM account
        """
        return __config__.get('password')

    @property
    def username(self) -> Optional[str]:
        """
        The username of the PHPIPAM account
        """
        return __config__.get('username')

