// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Address extends pulumi.CustomResource {
    /**
     * Get an existing Address resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AddressState, opts?: pulumi.CustomResourceOptions): Address {
        return new Address(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'phpipam:index/address:Address';

    /**
     * Returns true if the given object is an instance of Address.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Address {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Address.__pulumiType;
    }

    /**
     * The ID of the IP address in the PHPIPAM database.
     */
    public /*out*/ readonly addressId!: pulumi.Output<number>;
    /**
     * A key/value map of custom fields for this address.
     *
     * ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
     * all fields set to optional when using this plugin. For more info see
     * [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
     * ensure that your fields also do not have default values, or ensure the default
     * is set in your TF configuration. Diff loops may happen otherwise!
     * Custom fileds must contain mandatory prefix `custom_`.
     */
    public readonly customFields!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The description provided to this IP address.
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * The ID of the associated device in the PHPIPAM
     * database.
     */
    public readonly deviceId!: pulumi.Output<number>;
    /**
     * The last time this resource was modified.
     */
    public /*out*/ readonly editDate!: pulumi.Output<string>;
    /**
     * `true` if this address is excluded from ping
     * probes.
     */
    public readonly excludePing!: pulumi.Output<boolean>;
    /**
     * The hostname supplied to this IP address.
     */
    public readonly hostname!: pulumi.Output<string>;
    /**
     * The IP address to reserve.
     */
    public readonly ipAddress!: pulumi.Output<string>;
    /**
     * `true` if this IP address has been designated as a
     * gateway.
     */
    public readonly isGateway!: pulumi.Output<boolean>;
    /**
     * The last time this IP address answered ping probes.
     */
    public /*out*/ readonly lastSeen!: pulumi.Output<string>;
    /**
     * The MAC address provided to this IP address.
     */
    public readonly macAddress!: pulumi.Output<string>;
    /**
     * The note supplied to this IP address.
     */
    public readonly note!: pulumi.Output<string>;
    /**
     * The owner name provided to this IP address.
     */
    public readonly owner!: pulumi.Output<string>;
    /**
     * The ID of the associated PTR record in the
     * PHPIPAM database.
     */
    public readonly ptrRecordId!: pulumi.Output<number>;
    public readonly removeDnsOnDelete!: pulumi.Output<boolean | undefined>;
    /**
     * `true` if PTR records are not being created
     * for this IP address.
     */
    public readonly skipPtrRecord!: pulumi.Output<boolean>;
    /**
     * The tag ID in the database for the IP address'
     * specific state. **NOTE:** This is currently represented as an integer but may
     * change to the specific string representation at a later time.
     */
    public readonly stateTagId!: pulumi.Output<number>;
    /**
     * The database ID of the subnet this IP address
     * belongs to.
     */
    public readonly subnetId!: pulumi.Output<number>;
    /**
     * A string port label that is associated with
     * this address.
     */
    public readonly switchPortLabel!: pulumi.Output<string>;

    /**
     * Create a Address resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AddressArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AddressArgs | AddressState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AddressState | undefined;
            resourceInputs["addressId"] = state ? state.addressId : undefined;
            resourceInputs["customFields"] = state ? state.customFields : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["deviceId"] = state ? state.deviceId : undefined;
            resourceInputs["editDate"] = state ? state.editDate : undefined;
            resourceInputs["excludePing"] = state ? state.excludePing : undefined;
            resourceInputs["hostname"] = state ? state.hostname : undefined;
            resourceInputs["ipAddress"] = state ? state.ipAddress : undefined;
            resourceInputs["isGateway"] = state ? state.isGateway : undefined;
            resourceInputs["lastSeen"] = state ? state.lastSeen : undefined;
            resourceInputs["macAddress"] = state ? state.macAddress : undefined;
            resourceInputs["note"] = state ? state.note : undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["ptrRecordId"] = state ? state.ptrRecordId : undefined;
            resourceInputs["removeDnsOnDelete"] = state ? state.removeDnsOnDelete : undefined;
            resourceInputs["skipPtrRecord"] = state ? state.skipPtrRecord : undefined;
            resourceInputs["stateTagId"] = state ? state.stateTagId : undefined;
            resourceInputs["subnetId"] = state ? state.subnetId : undefined;
            resourceInputs["switchPortLabel"] = state ? state.switchPortLabel : undefined;
        } else {
            const args = argsOrState as AddressArgs | undefined;
            if ((!args || args.subnetId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subnetId'");
            }
            resourceInputs["customFields"] = args ? args.customFields : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["deviceId"] = args ? args.deviceId : undefined;
            resourceInputs["excludePing"] = args ? args.excludePing : undefined;
            resourceInputs["hostname"] = args ? args.hostname : undefined;
            resourceInputs["ipAddress"] = args ? args.ipAddress : undefined;
            resourceInputs["isGateway"] = args ? args.isGateway : undefined;
            resourceInputs["macAddress"] = args ? args.macAddress : undefined;
            resourceInputs["note"] = args ? args.note : undefined;
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["ptrRecordId"] = args ? args.ptrRecordId : undefined;
            resourceInputs["removeDnsOnDelete"] = args ? args.removeDnsOnDelete : undefined;
            resourceInputs["skipPtrRecord"] = args ? args.skipPtrRecord : undefined;
            resourceInputs["stateTagId"] = args ? args.stateTagId : undefined;
            resourceInputs["subnetId"] = args ? args.subnetId : undefined;
            resourceInputs["switchPortLabel"] = args ? args.switchPortLabel : undefined;
            resourceInputs["addressId"] = undefined /*out*/;
            resourceInputs["editDate"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Address.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Address resources.
 */
export interface AddressState {
    /**
     * The ID of the IP address in the PHPIPAM database.
     */
    addressId?: pulumi.Input<number>;
    /**
     * A key/value map of custom fields for this address.
     *
     * ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
     * all fields set to optional when using this plugin. For more info see
     * [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
     * ensure that your fields also do not have default values, or ensure the default
     * is set in your TF configuration. Diff loops may happen otherwise!
     * Custom fileds must contain mandatory prefix `custom_`.
     */
    customFields?: pulumi.Input<{[key: string]: any}>;
    /**
     * The description provided to this IP address.
     */
    description?: pulumi.Input<string>;
    /**
     * The ID of the associated device in the PHPIPAM
     * database.
     */
    deviceId?: pulumi.Input<number>;
    /**
     * The last time this resource was modified.
     */
    editDate?: pulumi.Input<string>;
    /**
     * `true` if this address is excluded from ping
     * probes.
     */
    excludePing?: pulumi.Input<boolean>;
    /**
     * The hostname supplied to this IP address.
     */
    hostname?: pulumi.Input<string>;
    /**
     * The IP address to reserve.
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * `true` if this IP address has been designated as a
     * gateway.
     */
    isGateway?: pulumi.Input<boolean>;
    /**
     * The last time this IP address answered ping probes.
     */
    lastSeen?: pulumi.Input<string>;
    /**
     * The MAC address provided to this IP address.
     */
    macAddress?: pulumi.Input<string>;
    /**
     * The note supplied to this IP address.
     */
    note?: pulumi.Input<string>;
    /**
     * The owner name provided to this IP address.
     */
    owner?: pulumi.Input<string>;
    /**
     * The ID of the associated PTR record in the
     * PHPIPAM database.
     */
    ptrRecordId?: pulumi.Input<number>;
    removeDnsOnDelete?: pulumi.Input<boolean>;
    /**
     * `true` if PTR records are not being created
     * for this IP address.
     */
    skipPtrRecord?: pulumi.Input<boolean>;
    /**
     * The tag ID in the database for the IP address'
     * specific state. **NOTE:** This is currently represented as an integer but may
     * change to the specific string representation at a later time.
     */
    stateTagId?: pulumi.Input<number>;
    /**
     * The database ID of the subnet this IP address
     * belongs to.
     */
    subnetId?: pulumi.Input<number>;
    /**
     * A string port label that is associated with
     * this address.
     */
    switchPortLabel?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Address resource.
 */
export interface AddressArgs {
    /**
     * A key/value map of custom fields for this address.
     *
     * ⚠️  **NOTE on custom fields:** PHPIPAM installations with custom fields must have
     * all fields set to optional when using this plugin. For more info see
     * [here](https://github.com/phpipam/phpipam/issues/1073). Further to this, either
     * ensure that your fields also do not have default values, or ensure the default
     * is set in your TF configuration. Diff loops may happen otherwise!
     * Custom fileds must contain mandatory prefix `custom_`.
     */
    customFields?: pulumi.Input<{[key: string]: any}>;
    /**
     * The description provided to this IP address.
     */
    description?: pulumi.Input<string>;
    /**
     * The ID of the associated device in the PHPIPAM
     * database.
     */
    deviceId?: pulumi.Input<number>;
    /**
     * `true` if this address is excluded from ping
     * probes.
     */
    excludePing?: pulumi.Input<boolean>;
    /**
     * The hostname supplied to this IP address.
     */
    hostname?: pulumi.Input<string>;
    /**
     * The IP address to reserve.
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * `true` if this IP address has been designated as a
     * gateway.
     */
    isGateway?: pulumi.Input<boolean>;
    /**
     * The MAC address provided to this IP address.
     */
    macAddress?: pulumi.Input<string>;
    /**
     * The note supplied to this IP address.
     */
    note?: pulumi.Input<string>;
    /**
     * The owner name provided to this IP address.
     */
    owner?: pulumi.Input<string>;
    /**
     * The ID of the associated PTR record in the
     * PHPIPAM database.
     */
    ptrRecordId?: pulumi.Input<number>;
    removeDnsOnDelete?: pulumi.Input<boolean>;
    /**
     * `true` if PTR records are not being created
     * for this IP address.
     */
    skipPtrRecord?: pulumi.Input<boolean>;
    /**
     * The tag ID in the database for the IP address'
     * specific state. **NOTE:** This is currently represented as an integer but may
     * change to the specific string representation at a later time.
     */
    stateTagId?: pulumi.Input<number>;
    /**
     * The database ID of the subnet this IP address
     * belongs to.
     */
    subnetId: pulumi.Input<number>;
    /**
     * A string port label that is associated with
     * this address.
     */
    switchPortLabel?: pulumi.Input<string>;
}
