// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFirstFreeAddress(args: GetFirstFreeAddressArgs, opts?: pulumi.InvokeOptions): Promise<GetFirstFreeAddressResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("phpipam:index/getFirstFreeAddress:getFirstFreeAddress", {
        "subnetId": args.subnetId,
    }, opts);
}

/**
 * A collection of arguments for invoking getFirstFreeAddress.
 */
export interface GetFirstFreeAddressArgs {
    /**
     * The ID of the subnet that the address resides in.
     *
     * **Example:**
     */
    subnetId: number;
}

/**
 * A collection of values returned by getFirstFreeAddress.
 */
export interface GetFirstFreeAddressResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress: string;
    readonly subnetId: number;
}
export function getFirstFreeAddressOutput(args: GetFirstFreeAddressOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFirstFreeAddressResult> {
    return pulumi.output(args).apply((a: any) => getFirstFreeAddress(a, opts))
}

/**
 * A collection of arguments for invoking getFirstFreeAddress.
 */
export interface GetFirstFreeAddressOutputArgs {
    /**
     * The ID of the subnet that the address resides in.
     *
     * **Example:**
     */
    subnetId: pulumi.Input<number>;
}
